<?php

/**
 * Implements hook_appstore_stores_info
 *
 * Add the ec app server
 */
function energycircle_apps_apps_servers_info() {
  $profile = variable_get('install_profile', 'ecdpanopoly');
  $info =  drupal_parse_info_file(drupal_get_path('profile', $profile) . '/' . $profile . '.info');
  return array(
    'energycircle' => array(
      'title' => 'EnergyCircle Apps',
      'description' => "Apps from EnergyCircle",
      'manifest' => '/profiles/ecdpanopoly/modules/ecfeature',
      'profile' => $profile,
      'profile_version' => isset($info['version']) ? $info['version'] : '7.x-1.x',
      'server_name' => $_SERVER['SERVER_NAME'],
      'server_ip' => $_SERVER['SERVER_ADDR'],
    ),
  );
}

/**
 * Implements hook_init()
 * 
 * Add a message if this is the ec apps page.
 */
function energycircle_apps_init() {
  if ($_GET['q'] == 'admin/apps/energycircle') {
    apps_include('manifest'); 
    $server = apps_servers('energycircle');
    // Create args array for substitutions
    $manifest = apps_manifest($server);
    if (isset($manifest['message']) && $manifest['message'] != '') {
      foreach($server as $key => $value) {
        $args['!' . $key] = $value;
      }
      drupal_set_message(format_string($manifest['message'], $args));
    }
  }
}
